# Generated by Django 5.2.8 on 2025-12-07 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistas', '0002_practica_delete_viaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='tours/')),
                ('duracion', models.CharField(max_length=50)),
            ],
        ),
    ]
