# Generated by Django 5.2.8 on 2025-12-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistas', '0003_tour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='imagen',
        ),
        migrations.AddField(
            model_name='tour',
            name='imagen_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
