# Generated by Django 5.2.8 on 2025-12-07 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistas', '0004_remove_tour_imagen_tour_imagen_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='practica',
            name='apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='practica',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='practica',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
