# Generated by Django 5.2.8 on 2025-12-07 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistas', '0005_practica_apellido_practica_email_practica_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='practica',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
