# Generated by Django 5.2.8 on 2025-12-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistas', '0006_practica_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='categoria',
            field=models.CharField(choices=[('ciudad', 'Ciudad'), ('lugar', 'Lugar')], default='ciudad', max_length=10),
        ),
    ]
